# - name: defining target group
#   hosts: arpit-roche
#   vars:
#     x: httpd
#     z: git
#   #become true means sudo access
#   become: true
#   tasks:
#    - name: testing ping module 
#      ping:

#    - name: running sample commands
#      command: date

#    - name: installing some software
#      yum:
#        name: 
#          - "{{ x }}"
#          - "{{ z }}"
#        state: present
#    - name: copy code to httpd app server location
#      copy:
#        src: my-apps/index.html
#        dest: /var/www/html/
#    - name: starting "{{x}}" service
#      service:
#         name: "{{x}}"
#         state: started
#         enabled: yes

- name: defining target group
  hosts: arpit-roche
  become: true
  roles: 
    - apache-webserver
