name: arpit devops job

#trigger point

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - "terraform.tfstate"

#creating jobs
jobs:
  test-job:
     runs-on: ubuntu-latest
     steps: #wht exactly the job would be doing
      - name: taking code from my repo
        uses: actions/checkout@v5
        with:
          ref: master
      #installing terraform
      - name: install "terraform.tfstate"
        uses: hashicorp/setup-terraform@v3
      #running some command
      - name: my first step to test github action
        run: |
          echo "hello world"
          git version
          whoami
          ls -a
          terraform version
<<<<<<< HEAD
      

  
=======
      
>>>>>>> dryrun-aws
