name: arpit devops job

#trigger point

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - "terraform.tfstate"

#creating jobs
jobs:
  infra-provision-job:
     runs-on: ubuntu-latest
     steps: #wht exactly the job would be doing
      - name: taking code from my repo
        uses: actions/checkout@v5
        with:
          ref: master
      #installing terraform
      - name: install "terraform.tfstate"
        uses: hashicorp/setup-terraform@v3
      #running some command
      - name: my first step to test github action
        run: |
          echo "hello world"
          git version
          whoami
          ls -a
          terraform version
      #configure aws access keys
      - name: connecting with AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: verifiy aws connection
        run: |
          echo "checking with command"
          aws s3 ls 
      - name: deploy terraform resources 
        run: |
          echo "implementing terraform deals"
          terraform init 
          terraform plan 
          sleep 2
          terraform apply --auto-approve
          ls modules/ec2
#creating aritfact and uploading ansible inventory file
      - name: uploading ansible inventory to git artifacts
        uses : actions/upload-artifact@v4
        with:
          name: arpit-github-artifact
          path: modules/ec2/ansible-inventory.txt

  infra-destroy-job:
    needs: infra-provision-job
    runs-on: ubuntu-latest
    steps:
    - name: checking out code 
      uses: actions/checkout@v5
      with:
        ref: master 
    - name: login to aws creds 
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    # installing  
    - name: installing terraform 
      uses: hashicorp/setup-terraform@v3
#downloading artifact
    - name: downloading ansible inventory from git artifacts
      uses: actions/download-artifact@v5
      with:
         name: arpit-github-artifact

    - name: destroying it 
      run: | 
        echo "checking resoruces"
        terraform init 
        terraform state list
        terraform destroy --auto-approve

  